### ISSUE TITLE
i'm not able use it with image picker plugin

### ISSUE THREAD

**Issue by ChannakeshavaGowda6** [pycampers/flutter_pdf_viewer#14] opened 2019-02-07 22:21 UTC
when i use it separately  its working but not with image picker plugin

**Comment by devxpy** [comment] 2019-02-08 01:17
Thank you for the report!

Can I please have some more debug information?

## Steps to Reproduce

Please tell us exactly how to reproduce the problem you are running into.

 Please attach a small application (ideally just one main.dart file) that
 reproduces the problem. You could use https://gist.github.com/ for this.

 If the problem is with your application's rendering, then please attach
 a screenshot and explain what the problem is.      

## Logs

Run your application with `flutter run --verbose` and attach all the
log output below between the lines with three backticks. If there is an
exception, please see if the error message includes enough information
to explain how to solve the issue.

Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

 Finally, paste the output of running `flutter doctor -v` here.

**Comment by ChannakeshavaGowda6** [comment] 2019-02-08 21:23
/Users/channakeshavagowda/developmant/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pdf_viewer-0.0.7/android
/src/main/kotlin/com/pycampers/flutterpdfviewer/FlutterPdfViewerPlugin.kt: (8, 27): Unresolved reference: content
[   +9 ms] e:
/Users/channakeshavagowda/developmant/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pdf_viewer-0.0.7/android
/src/main/kotlin/com/pycampers/flutterpdfviewer/FlutterPdfViewerPlugin.kt: (37, 27): Unresolved reference:
LocalBroadcastManager
[        ] e:
/Users/channakeshavagowda/developmant/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pdf_viewer-0.0.7/android
/src/main/kotlin/com/pycampers/flutterpdfviewer/FlutterPdfViewerPlugin.kt: (37, 51): Unresolved reference:
LocalBroadcastManager
[        ] e:
/Users/channakeshavagowda/developmant/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pdf_viewer-0.0.7/android
/src/main/kotlin/com/pycampers/flutterpdfviewer/PdfActivity.kt: (8, 27): Unresolved reference: content
[        ] e:
/Users/channakeshavagowda/developmant/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pdf_viewer-0.0.7/android
/src/main/kotlin/com/pycampers/flutterpdfviewer/PdfActivity.kt: (108, 41): Unresolved reference:
LocalBroadcastManager
[        ] e:
/Users/channakeshavagowda/developmant/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pdf_viewer-0.0.7/android
/src/main/kotlin/com/pycampers/flutterpdfviewer/PdfActivity.kt: (148, 33): Unresolved reference:
LocalBroadcastManager
[        ] e:
/Users/channakeshavagowda/developmant/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pdf_viewer-0.0.7/android
/src/main/kotlin/com/pycampers/flutterpdfviewer/PlayerController.kt: (5, 27): Unresolved reference: content
[        ] e:
/Users/channakeshavagowda/developmant/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pdf_viewer-0.0.7/android
/src/main/kotlin/com/pycampers/flutterpdfviewer/PlayerController.kt: (34, 32): Unresolved reference:
LocalBroadcastManager
[        ] e:
/Users/channakeshavagowda/developmant/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pdf_viewer-0.0.7/android
/src/main/kotlin/com/pycampers/flutterpdfviewer/PlayerController.kt: (34, 56): Unresolved reference:
LocalBroadcastManager
[  +47 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':flutter_pdf_viewer:compileDebugKotlin'.
[        ] > Compilation error. See log for more details
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 29s
[        ] > Task :flutter_pdf_viewer:compileDebugKotlin FAILED
[        ] 86 actionable tasks: 49 executed, 37 up-to-date
[ +386 ms] Running Gradle task 'assembleDebug'... (completed in 29.9s)
[   +7 ms] "flutter run" took 41,851ms.
[        ] "flutter run" took 41,851ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:418:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:310:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:378:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:308:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:551:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#18     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#26     Future._complete (dart:async/future_impl.dart:473:7)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#28     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#29     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#30     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#31     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#36     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#37     Future._complete (dart:async/future_impl.dart:473:7)
#38     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#39     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by devxpy** [comment] 2019-02-09 03:31
Can you please try out the master branch?

Put this in the `pubspec.yaml`. 
```
  flutter_pdf_viewer:
    git: https://github.com/pycampers/flutter_pdf_viewer
```


(P.S. master branch has the downloader API removed)

**Comment by ChannakeshavaGowda6** [comment] 2019-02-09 16:31
devxpy thank you so much bro

**Comment by ChannakeshavaGowda6** [comment] 2019-02-15 16:49
flutter_pdf_viewer:
    git: https://github.com/pycampers/flutter_pdf_viewer 

it will work but downloadASflile function is not found

**Comment by devxpy** [comment] 2019-02-20 05:19
Downloader feature has been removed. Like I said earlier, its bettee implemented in a separate library. Use something like http or dio.

**Closed** 2019-03-21 10:08 UTC
